### PR TITLE
Add a slew of version info to the About dialog

### PR DESCRIPTION
**Pull request by cquammen**
Partially addresses request in #746.

Looks like:

image

### CODE REVIEW

**Comment by cquammen** [comment]
It would be good to test this against Python 3 if anyone has a Tomviz built against Python 3 laying around.

**Comment by cjh1** [comment]
@cquammen I can test against Python 3

File: tomviz/AboutDialog.cxx [hunk 1]
```diff
@@ -24,23 +24,95 @@
...
+#if PY_MAJOR_VERSION >= 3
+      const char* cdata = PyUnicode_AsUTF8(attr);
+#else
+      const char* cdata = PyBytes_AsString(attr);
+#endif
+      AddItem(tree, itemName, QString::fromStdString(cdata ? cdata : ""));
+    }
+  } else {
+    AddItem(tree, itemName, "unavailable");
+  }
```
Comment (cjh1) [inline tomviz/AboutDialog.cxx]: @cquammen This doesn't compile with Python 3, because Qt defines slots as well as Python 3. I have already created classes in [PythonUtilities] (https://github.com/OpenChemistry/tomviz/blob/master/tomviz/PythonUtilities.h) then encapsulates our python operations, for example you can import a module using this [function](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/PythonUtilities.h#L142). You make have to add some API to do what you want. The ideal is to not leak any python types.

Comment (cquammen) [inline tomviz/AboutDialog.cxx]: Not sure I follow the comment about Qt and Python 3 slots. I should be able to use the Python wrapper. By leaking python types, do you mean exposing them within the core Tomviz code itself?

Comment (cjh1) [inline tomviz/AboutDialog.cxx]: Correct, python type should only be used in PythonUtilities.cxx. I can provide assistance if you run into any issues.

**Comment by cquammen** [comment]
Okay, @cjh1, I think we're on the same page now. How's this?

File: tomviz/AboutDialog.cxx [hunk 2]
```diff
@@ -20,27 +20,96 @@
...
+  AddItem(tree, "Qt Version", QString(QT_VERSION_STR));
+
+  AddPythonAttributeItem(tree, "Python Path", "sys", "prefix");
+  AddPythonAttributeItem(tree, "Python Version", "sys", "version");
+  AddPythonAttributeItem(tree, "NumPy Version", "numpy", "__version__");
+  AddPythonAttributeItem(tree, "NumPy Path", "numpy", "__file__");
+  AddPythonAttributeItem(tree, "SciPy Version", "scipy", "__version__");
+  AddPythonAttributeItem(tree, "SciPy Path", "scipy", "__file__");
+
+#if QT_VERSION >= 0x050000
```
Comment (cryos) [inline tomviz/AboutDialog.cxx]: We don't need this version check, we have a hard requirement of Qt 5

File: tomviz/AboutDialog.cxx [hunk 3]
```diff
@@ -20,27 +20,96 @@
...
+                                          const char* module,
+                                          const char* attribute)
+{
+  Python::initialize();
+
+  bool itemAdded = false;
+  Python py;
+  Python::Module mod = py.import(QString(module));
+  if (mod.isValid()) {
+    Python::Function func = mod.findFunction(QString(attribute));
```
Comment (cjh1) [inline tomviz/AboutDialog.cxx]: Glad you didn't have to add anything to PythonUtilities, looks a little odd the naming thought, looking up an attribute with findFunction(...), I wonder if we need to do some renaming, but I can let it go :snowflake:

Comment (cquammen) [inline tomviz/AboutDialog.cxx]: But... I did add a toString() function to object. I agree the naming is funny - I could add a `findAttribute()` function.

**Comment by cryos** [comment]
This looks great, although I tried with Python 2, my one concern is whether the Python, NumPy, and SciPy paths are useful or might end up being confusing. Maybe moving them all to the bottom would be better as advanced information (keeping the versions at the top).

File: tomviz/AboutDialog.cxx (hunk 3 above)
Comment (cquammen) [inline tomviz/AboutDialog.cxx]: But that might require a `Python::Attribute` class. Not sure if it is worth it.

Comment (cjh1) [inline tomviz/AboutDialog.cxx]: Sorry, yes, I didn't notice that. I am happy for you to leave as is.

**Comment by cjh1** [comment]
For some request my PYTHONPATH get reported as /usr, strange?

screen

**Comment by cryos** [comment]
Mine does too, but looking at Cory's screenshot it is reporting the prefix path. This is why I think putting the paths at the end makes sense, or possibly removing them if they become a point of confusion. It is great debug information if we have issues. I think ideally the whole thing would be available in a JSON/XML file that could be saved, and displayed like this.

**Comment by cryos** [comment]
Can we show the full Python path, or rename this to Python Prefix perhaps?

**Comment by cquammen** [comment]
Honest question: what would the full Python path? It wouldn't be the python executable as that is Tomviz itself. The shared library file?

I'll change the name to "Python Prefix" for now.

**Comment by cryos** [comment]
For me it would be the path to the Python executable, on Linux you often have different python binaries living in the /usr prefix, commonly a python, python2 and python3. All you are showing is the prefix, so changing the label seems to make sense. Chris also thought it might have been PYTHONPATH environment variable, which I hadn't thought of. Thanks for changing the label, I think certain names evoke certain expectations that may be influenced by the OS you use (macOS path is much more useful than /usr on Linux which is the common prefix for all system installed binaries).

**Comment by cryos** [comment]
I am seeing this link error with my Python 3 build:

[ 96%] Linking CXX executable ../bin/tomviz
libtomviz.a(PythonUtilities.cxx.o): In function `tomviz::Python::Object::toString() const':
/home/marcus/src/tomviz/tomviz/PythonUtilities.cxx:116: undefined reference to `PyString_AsString'
libtomviz.a(PythonUtilities.cxx.o): In function `tomviz::Python::Dict::toString()':
/home/marcus/src/tomviz/tomviz/PythonUtilities.cxx:211: undefined reference to `PyString_AsString'
libtomviz.a(PythonUtilities.cxx.o): In function `tomviz::Python::toPyObject(QString const&)':
/home/marcus/src/tomviz/tomviz/PythonUtilities.cxx:361: undefined reference to `PyUnicodeUCS4_DecodeUTF16'
libtomviz.a(PythonUtilities.cxx.o): In function `tomviz::Python::toPyObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/marcus/src/tomviz/tomviz/PythonUtilities.cxx:366: undefined reference to `PyString_FromStringAndSize'
libtomviz.a(PythonUtilities.cxx.o): In function `tomviz::Python::toPyObject(tomviz::Variant const&)':
/home/marcus/src/tomviz/tomviz/PythonUtilities.cxx:378: undefined reference to `_Py_ZeroStruct'
libtomviz.a(PythonUtilities.cxx.o): In function `tomviz::Python::toPyObject(long)':
/home/marcus/src/tomviz/tomviz/PythonUtilities.cxx:408: undefined reference to `PyInt_FromLong'
collect2: error: ld returned 1 exit status

**Comment by cquammen** [comment]
@cryos Does master compile with your Python 3? A number of the linker errors you report stem from code not introduced by this PR. Also, Chris is able to compile with Python 3.5.2 (as helpfully reported in his screenshot).

**Comment by cryos** [comment]
Current master does compile, but the tip of this branch does not. This is Python 3.6.0 on Arch Linux, my laptop using Python 3.5.2 on Ubuntu does compile and link with this branch, so perhaps it is a change in 3.6. I found https://docs.python.org/2/c-api/string.html stating it is moving to PyBytes but should be aliased in Python 3.

**Comment by cquammen** [comment]
This branch adds `QString Python::Object::toString() const`. Have you any idea where the other linker failures are coming from? Also, if there is a change in Python 3.6, why isn't there a failure when compiling `PythonUtilities.cxx`. If those functions are gone from 3.6, I would expect an earlier compilation failure, not a linker failure.

**Comment by cryos** [comment]
I am just digging into it too, I am surprised. I have confirmed that /usr/include/python3.6m is being used, which is the correct include path, and /usr/lib64/libpython3.6m.so is being linked to. Switching back to master gives me a successful build, switching back does not. I rebased your branch on master, and still see the same link failure.

**Comment by cryos** [comment]
Commenting out your ITK lines makes everything work/link fine for me. I think something in there is causing issues with my include path, adding the 
    include_directories(${ITK_INCLUDE_DIRS})
back causing link failures. I then went and inspected the ITK build and it had reverted to Python 2 at some point. Changing that things build, so I think this is a local configuration issue, but we should add a CMake check. ITK also adds lots of include directories to the global build path (much as ParaView does), which is a shame especially as it is only used to get the version information.

**Comment by cryos** [comment]
We can do the above in a follow up commit, long and short is everything seems to work OK but verification of consistent Python versions in ParaView (which we use to set our Python version) and ITK (which we do not) is more important if we are adding it to our include path. Bad things would have happened later when running ITK code, error at CMake time is preferable.

**Comment by cryos** [comment]
That would be good, as I feared this branch is causing build failures on the buildbot machines, e.g. https://open.cdash.org/viewBuildError.php?buildid=4809771 for one. I don't think they necessarily made ITK available during Tomviz configure, and simply packaged it after. We will need to get that figured out, or back off on the ITK stuff being required.

**Comment by cquammen** [comment]
Drat, I'll push a branch to clean things up.

**Comment by cryos** [comment]
No worries, I wanted to see if it would work or not. It might not be too hard to ensure Tomviz can see the ITK build at configure time.
