### ISSUE TITLE
Missing liblapack.so from Tomviz 1.2.0 Linux package

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1312]
When running the gradient magnitude 2D from the preprocessing menu under tomography menu I get,
$ ./Tomviz-1.2.0-Linux-64bit/bin/tomviz 
Traceback (most recent call last):
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/tomviz/site-packages/tomviz/utils.py", line 20, in <module>
    import numpy as np
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/linalg/__init__.py", line 50, in <module>
    from .linalg import *
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: liblapack.so: cannot open shared object file: No such file or directory
Failed to import tomviz.utils module.

**Comment by mathturtle** [comment]
I seem to remember fixing that recently... I'll take a look this afternoon.

**Comment by cryos** [comment]
Further testing reveals most operators using numpy fail in various ways for me. It looks quite generally broken on Linux (here at least). Even shift volume gives,

Traceback (most recent call last):
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/tomviz/site-packages/tomviz/utils.py", line 20, in <module>
    import numpy as np
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/python3.6/site-packages/numpy/lib/polynomial.py", line 13, in <module>
    import numpy.core.numeric as NX
AttributeError: module 'numpy' has no attribute 'core'
Failed to import tomviz.utils module.

**Comment by cryos** [comment]
If this is a packaging issue it would be great to get this fixed ASAP, and see if I can get a new binary up by tomorrow afternoon.

**Comment by cryos** [comment]
I see package creation is now failing, https://open.cdash.org/viewTest.php?onlyfailed&buildid=5114591 shows the failure after merging the extra CMake to the superbuild.

**Comment by mathturtle** [comment]
It is timing out.  Processing all the dependencies is slow...  I'll try increasing the test timeout and see what happens.

**Comment by cryos** [comment]
If I read it right the time was over one hour, which seems unsustainable to me longer term, is it not possible to be a little more targeted with the additional files/directories?

**Comment by mathturtle** [comment]
I'm trying a build that is more selective now to see what the difference in time is.  I'll push it once it finishes and I know it still packages lapack.so

**Comment by mathturtle** [comment]
I'm not sure it helped much, but I pushed a version that only installs dependencies of `site-packages/numpy` and `site-packages/scipy`.  Locally the packaging time is about the same though...

**Comment by mathturtle** [comment]
The most recent version (from yesterday) has `liblapack.so` and `libblas.so`.  I just hardcoded it to package those, any time we call the install_dependencies script it is so slow that it times out, even if I limit it to just the dependencies of numpy/scipy.

**Comment by cryos** [comment]
Sounds good, sorry about the lack of reply, hectic course and then travel, and pretty wiped out after getting back. I can give these a try and see if they are more functional.

**Comment by cryos** [comment]
This was fixed in the 1.2.1 release binaries, verified on an independent system. Thanks.
